# This file contains the parameters for the credentials used in the workflows.
# You can use `az ad sp create-for-rbac --sdk-auth` to create service principal credentials
# You can set AZURE_CREDENTIALS values with multiple line secrets
# Here is an example
# - name: AZURE_CREDENTIALS
#   value: |
#      {
#       "clientId": "<clientId>",
#       "clientSecret": "<clientSecret>",
#       "subscriptionId": "<subscriptionId>",
#       "tenantId": "<tenantId>",
#       "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
#       "resourceManagerEndpointUrl": "https://management.azure.com/",
#       "activeDirectoryGraphResourceId": "https://graph.windows.net/",
#      }
#   description: Azure Credentials used for workflows.
- name: AZURE_CREDENTIALS
  value: ""
  description: Azure Credentials used for *WlsAks*.yml and *WlsVm*.yml workflows.
- name: ORC_SSOUSER
  value: ""
  description: "Oracle single sign-on userid."
- name: ORC_SSOPSW
  value: ""
  description: "Password for Oracle single sign-on userid."
- name: WDT_RUNTIMEPSW
  value: ""
  description: "Password for WebLogic Server and Runtime Deployment Tooling encryption."
- name: WLS_PSW
  value: ${WDT_RUNTIMEPSW}
  description: "Password for WebLogic Server and Runtime Deployment Tooling encryption."
# parameters for the credentials used in the workflows with default values.
- name: WLS_USERNAME
  value: "weblogic"
  description: "WebLogic Server user name."
- name: DB_PASSWORD
  value: "Secret123!"
  description: "Password for the database"
- name: LOCATION
  value: "eastus"
  description: "Location of the resource group"